src/objects/CityManager__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CityManagers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CityManager</label>
    <nameField>
        <displayFormat>CMN-{0000}</displayFormat>
        <label>CityManagerNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CityManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Maths</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>CityManager__c</fullName>
        <label>CityManager</label>
        <referenceTo>CityManager__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>CityManager__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Custom_Status__c</fullName>
        <label>Custom Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>Reset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TriggersTest.cls
@isTest
private class TriggersTest {
    private testMethod static void testDisallowDeletionOfClassWithFemaleStudents(){
        Class__c cls = new Class__c(ClassName__c = 'C1', MaxSize__c = 100);
        insert cls;
        List<Student__c> students = new List<Student__c>();
        Student__c student = new Student__c(LastName__c = 'Female', Class__c = cls.Id, Sex__c = 'Female');
        students.add(student);
        for(Integer i = 0; i < 99; i++){
            students.add(new Student__c(LastName__c = 'Male' + (i + 1), Class__c = cls.Id, Sex__c = 'Male'));
        }
        insert students;
        try{
            delete cls;
            System.assert(false, 'Class should not have been deleted');
        }catch(Exception e){
            System.assert(e.getMessage().contains('Cannot delete a class with female students'), 'Expected error to contain \'Cannot delete a class with female students\'');
        }
        System.assertEquals(1, [SELECT COUNT() FROM Class__c]);
        System.assertEquals(100, [SELECT COUNT() FROM Student__c]);
    }
    
    private static testMethod void testDisallowInsertionUpdationOfHindiTeacher(){
        Contact hindiTeacher = new Contact(LastName = 'XXX', Subjects__c = 'Hindi;English;Maths');
        try{
        	insert hindiTeacher;
            System.assert(false, 'Record should not have been inserted');
        }catch(Exception e){
            System.assert(e.getMessage().contains('We don\'t want anymore Hindi Teachers and Hindi Teacher\'s records cannot be updated'), 'Expected error to contain \'We don\'t want anymore Hindi Teachers and Hindi Teacher\'s records cannot be updated\' got ' + e.getMessage());
        }
        
        Contact englishTeacher = new Contact(LastName = 'XXX', Subjects__c = 'English;Maths');
        insert englishTeacher;
        englishTeacher.Subjects__c = 'English;Maths;Hindi';
        try{
        	update englishTeacher;
            System.assert(false, 'Record should not have been updated');
        }catch(Exception e){
            System.assert(e.getMessage().contains('We don\'t want anymore Hindi Teachers and Hindi Teacher\'s records cannot be updated'), 'Expected error to contain \'We don\'t want anymore Hindi Teachers and Hindi Teacher\'s records cannot be updated\' got ' + e.getMessage());
        }
    }
    
    private testMethod static void testOpportunityCloseDate(){
        Opportunity opp1 = new Opportunity(Name = 'Test Opp', StageName = 'Prospecting', CloseDate=Date.newInstance(2018, 1, 1));
        insert opp1;
        opp1.StageName = 'Closed Won';
        update opp1;
        opp1 = [SELECT CloseDate FROM Opportunity WHERE Id = :opp1.Id];
        System.assertEquals(Date.today(), opp1.CloseDate);
    }
    
    private testMethod static void testOpportunityReset(){
        Opportunity opp1 = new Opportunity(Name = 'Test Opp', StageName = 'Prospecting', CloseDate=Date.newInstance(2018, 1, 1));
        insert opp1;
        Id pricebookId = Test.getStandardPricebookId();
		Product2 prod = new Product2(Name = 'Product X', ProductCode = 'Pro-X', isActive = true);
		insert prod;
        PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id, UnitPrice = 100.00, IsActive = true);
		insert pbEntry;
        List<OpportunityLineItem> oppLitems = new List<OpportunityLineItem>();
        for(Integer i = 0; i < 200; i++){
            oppLitems.add(new OpportunityLineItem(OpportunityId = opp1.Id, Quantity = 2, PricebookEntryId = pbEntry.Id, TotalPrice = 200));
        }    
		insert oppLitems;
        opp1.Custom_Status__c = 'Reset';
        update opp1;
        System.assertEquals(0, [SELECT COUNT() FROM OpportunityLineItem]);
    }
    
    private static testMethod void testHandleLoanInsert(){
        List<CityManager__c> cityManagers = new List<CityManager__c>();
        for(Integer i = 0; i < 100; i++){
            cityManagers.add(new CityManager__c(City__c = 'Test City' + i, Manager__c = UserInfo.getUserId()));
        }
        insert cityManagers;
        cityManagers = [SELECT Id, Manager__c FROM CityManager__c ORDER BY Name];
        List<Loan__c> loans = new List<Loan__c>();
        for(Integer i = 0; i < 100; i++){
            loans.add(new Loan__c(Name = 'Test Loan' + i, CityManager__c = cityManagers.get(i).Id));
        }
        insert loans;
        loans = [SELECT Id, Manager__c FROM Loan__c ORDER BY Name];
        System.assertEquals(cityManagers.get(0).Manager__c, loans.get(0).Manager__c);
    }
    
    private static testMethod void testHandleMyCountAndMaxSize(){
        Class__c cls = new Class__c(ClassName__c = 'XXX', MaxSize__c = 100);
        insert cls;
        List<Student__c> students = new List<Student__c>();
        for(Integer i = 0; i < 50; i++){
            students.add(new Student__c(LastName__c = 'ST' + i, Class__c = cls.Id));
        }
        insert students;
        cls = [SELECT Id, MyCount__c FROM Class__c];
        System.assertEquals(50, cls.MyCount__c);
        cls.MyCount__c = 51;
        update cls;
        cls = [SELECT Id, MyCount__c, MaxSize__c FROM Class__c];
        System.assertEquals(51, cls.MyCount__c);
        students = new List<Student__c>();
        for(Integer i = 0; i < 51; i++){
            students.add(new Student__c(LastName__c = 'ST' + i, Class__c = cls.Id));
        }
        
        try{
            insert students;
            System.assert(false, 'Error was expected while inserting students');
        }catch(Exception e){
            System.assert(e.getMessage().contains('The class has already reached it\'s maximum size of ' + cls.MaxSize__c + '. More Students cannot be added'), e.getMessage());
        }
            
    }
}