src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClassManager.cls
//This class handles operations on the Class__c Sobject
public class ClassManager {
    //Takes classid as a parameter and returns the list of the names of all students
    public static List<String> getStudents(Id classid){
        List<String> studentNames = new List<String>();
        for(Student__c student : [SELECT FirstName__c, LastName__c FROM Student__c WHERE Class__c = :classid]){
            studentNames.add(student.FirstName__c + ' ' + student.LastName__c);
        }
        return studentNames;
    }
    
    //Returns a mapping of class and the set of the Ids of all students in it
    public static Map<Id, Set<Id>> getStudents(){
        Map<Id, Set<Id>> studentsInClass = new Map<Id, Set<Id>>();
        List<Student__c> students = [SELECT Id, Class__c FROM Student__c];
        for(Student__c student : students){
            if(studentsInClass.get(student.class__c) != null){
                studentsInClass.get(student.Class__c).add(student.Id);
            }else{
                studentsInClass.put(student.Class__c, new Set<Id>{student.Id});
            }
        }
        return studentsInClass;
    }
}