src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Custom_Name__c</fullName>
        <formula>IF(NOT(OR(ISBLANK(FirstName__c),ISNULL(FirstName__c))), FirstName__c &amp; &apos; &apos;, &apos;&apos;) &amp; LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Married__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Married</label>
        <type>Checkbox</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentWebsiteController.cls
public class StudentWebsiteController {
    public String selectedStudentName{get;set;}
    public Set<String> studentNames{get;set;}
    public List<Student__c> students{get;set;}
    public StudentWebsiteController(){
        students = new List<Student__c>();
        studentNames = new Set<String>();
        for(Student__c student : [SELECT Id, Custom_Name__c FROM Student__c ORDER BY Custom_Name__c]){
            studentNames.add(student.Custom_Name__c);
        }
        System.debug(selectedStudentName);
    }
    
    public PageReference loadRecords(){
        System.debug(selectedStudentName);
        students = [SELECT Id, Custom_Name__c, DOB__c, Married__c, Class__r.Name FROM Student__c WHERE Custom_Name__c = :selectedStudentName];
        System.debug(students);
        return null;
    }

}