src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RAJ</fullName>
                </value>
                <value>
                    <fullName>CBSE</fullName>
                </value>
                <value>
                    <fullName>BIHAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManageClassesController.cls
public class ManageClassesController {
    //public ApexPages.StandardSetController controller{get;set;}
    public List<Class__c> classes{get;set;}
    public Id recordId{get;set;}
    public Class__c mockClass{get;set;}
    public Boolean isRecordBeingEdited{get;set;}
    public ManageClassesController(){
                fetchRecords();
    }
    
    public void deleteRecord(){
        System.debug(recordId);
        delete [SELECT Id FROM Class__c WHERE Id = :recordId];    
        fetchRecords();
        isRecordBeingEdited = false;
    }
    
    public void edit(){
        isRecordBeingEdited = true;
        mockClass = [SELECT Id, ClassName__c, Fee__c, ClassTeacher__c, Board__c, MaxSize__c FROM Class__c WHERE Id = :recordId];
    }
    
    public void saveRecord(){
        Class__c cls = new Class__c(Id = mockClass.Id,ClassName__c = mockClass.ClassName__c,
                                    Fee__c = mockClass.Fee__c,
                                    Board__c = mockClass.Board__c,
                                    MaxSize__c = mockClass.MaxSize__c,
                                    ClassTeacher__c = mockClass.ClassTeacher__c);
        update cls;
        fetchRecords();
        isRecordBeingEdited = false;
    }
    
    public void cancel(){
        mockClass = new Class__c();
        isRecordBeingEdited = false;
    }
    
    public void fetchRecords(){
        //controller = new ApexPages.StandardSetController([SELECT Id, ClassName__c, Fee__c, ClassTeacher__c, Board__c, MaxSize__c FROM Class__c]);
        //classes = controller.getRecords();
        classes = [SELECT Id, ClassName__c, Fee__c, ClassTeacher__c, Board__c, MaxSize__c FROM Class__c];
    }
}