src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentAsPDFExtensionTest.cls
@isTest
private class StudentAsPDFExtensionTest {
    private static testMethod void testPDFExtension(){
    	Class__c cls = new Class__c(ClassName__c = 'C1', MaxSize__c = 100);
     	insert cls;
     	Student__c student = new Student__c(LastName__c = 'XXX', Class__c = cls.Id);
     	insert student;
        Test.setCurrentPage(Page.StudentAsPDF);
        StudentAsPDFExtension ext = new StudentAsPDFExtension(new ApexPages.StandardController(student));
        String redirectUrl = ext.saveAsPDF().getUrl();
        String expectedUrl = new PageReference('/' + student.Id).getUrl();
        System.assertEquals(expectedUrl, redirectUrl);
        List<Attachment> content = [SELECT Id, Body, ContentType, Name FROM Attachment WHERE ParentID = :student.Id];
        System.assertEquals(1, content.size());
        System.assertEquals(Blob.valueOf(student.Id), content[0].Body);
        System.assertEquals('application/pdf', content[0].ContentType);
        System.assertEquals('Student Details.pdf', content[0].Name);
    }
}