src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteStudentsControllerTest.cls
@isTest
private class DeleteStudentsControllerTest {
    private testMethod static void testDeleteRecords(){
        Class__c cls = new Class__c(ClassName__c = 'C1', MaxSize__c = 100);
        insert cls;
        Student__c student = new Student__c(LastName__c = 'XXX', Class__c = cls.Id);
        insert student;
        ApexPages.StandardSetController stdSetcntrl = new ApexPages.StandardSetController(new List<Student__c>{student});
        stdSetcntrl.setSelected(new List<SObject>{student});
        DeleteStudentsController controller = new DeleteStudentsController(stdSetcntrl);
        String redirectUrl = controller.deleteRecords().getUrl();
        System.assertEquals(stdSetcntrl.cancel().getUrl(), redirectUrl);
        System.assertEquals(0, [SELECT COUNT() FROM Student__c]);
    }
    
    private testMethod static void testcancel(){
        Class__c cls = new Class__c(ClassName__c = 'C1', MaxSize__c = 100);
        insert cls;
        Student__c student = new Student__c(LastName__c = 'XXX', Class__c = cls.Id);
        insert student;
        ApexPages.StandardSetController stdSetcntrl = new ApexPages.StandardSetController(new List<Student__c>{student});
        stdSetcntrl.setSelected(new List<SObject>{student});
        DeleteStudentsController controller = new DeleteStudentsController(stdSetcntrl);
        String redirectUrl = controller.cancel().getUrl();
        System.assertEquals(stdSetcntrl.cancel().getUrl(), redirectUrl);
        System.assertEquals(1, [SELECT COUNT() FROM Student__c]);
    }
    
    private testMethod static void testError(){
        Class__c cls = new Class__c(ClassName__c = 'C1', MaxSize__c = 100);
        insert cls;
        Student__c student = new Student__c(LastName__c = 'XXX', Class__c = cls.Id);
        insert student;
        ApexPages.StandardSetController stdSetcntrl = new ApexPages.StandardSetController(new List<Student__c>{student});
        Test.setCurrentPage(Page.DeleteStudents);
        DeleteStudentsController controller = new DeleteStudentsController(stdSetcntrl);
        System.assert(ApexPages.hasMessages(ApexPages.Severity.ERROR));
       
        System.assertEquals('No records selected', ApexPages.getMessages().get(0).getSummary());
    }


}