src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaxSize__c</fullName>
        <label>MaxSize</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>CLS-{0000}</displayFormat>
        <label>ClassId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ClassManagerTest.cls
@isTest
private class ClassManagerTest {
    @testSetup
    private static void setup(){
        class__c cls1, cls2;
    	Student__c student1, student2, student3, student4;
    	cls1 = new Class__c(ClassName__c = 'C1', MaxSize__c = 100);
        cls2 = new Class__c(ClassName__c = 'C2', MaxSize__c = 100);
        system.debug(cls1);
        insert new List<Class__c>{cls1, cls2};
        student1 = new Student__c(LastName__c = 'XXX', Class__c = cls1.Id);
        student2 = new Student__c(LastName__c = 'XXY', FirstName__c = 'aaa', Class__c = cls1.Id);
        student3 = new Student__c(LastName__c = 'XXZ', Class__c = cls2.Id);
        student4 = new Student__c(LastName__c = 'XYY', Class__c = cls2.Id);
        insert new List<Student__c>{student1, student2, student3, student4};
    } 
    private testMethod static void testGetStudentsAsList(){
        Id classId = [SELECT Id FROM Class__c WHERE className__c = 'C1'].Id;
    	List<String> students = ClassManager.getStudents(classId);
        System.assertEquals(new List<String>{'XXX','aaa XXY'}, students);
    }
    
    private testMethod static void testGetStudentIdsAsMap(){
        Map<Id, Set<Id>> classMap = ClassManager.getStudents();
        List<Class__c> classes = [SELECT Id FROM Class__c ORDER BY Name];
        List<Student__c> students = [SELECT Id FROM Student__c ORDER BY LastName__c];
        System.assertEquals(new Map<Id, Set<Id>>{
            classes[0].Id => new Set<Id>{
                students[0].Id, Students[1].id},
            classes[1].Id => new Set<Id>{
                students[2].Id, Students[3].id}}, classMap);
        	
        
    }

}