src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Maths</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BillToContactLookupController.cls
public class BillToContactLookupController {
    public Opportunity opp{get;set;}
    public List<SelectOption> options{get;set;}
    public List<Contact> contacts{get;set;}
    public Id selectedContactId{get;set;}
    public BillToContactLookupController(){
        Id opportunityId = ApexPages.currentPage().getParameters().get('oppId');
        options = new List<SelectOption>();
        opp = [SELECT Id, Bill_To_Contact__c, Manager__c, Manager__r.Name FROM Opportunity WHERE Id = :opportunityId];
        selectedContactId = opp.Bill_To_Contact__c;
        contacts = [SELECT Id, Name, Subjects__c, Account.Name FROM Contact WHERE (AccountId != NULL AND AccountId = :opp.Manager__c) ORDER BY NAME];
        for(Contact c : contacts){
            options.add(new SelectOption(c.Id, 'Name : ' + c.Name + ' Subjects : ' + c.Subjects__c));
        }
    }
    
    public PageReference save(){
        opp.Bill_To_Contact__c = selectedContactId;
        update opp;
        return redirectToOpportunity();
    }
    
    public PageReference clear(){
        opp.Bill_To_Contact__c = null;
        update opp;
        return redirectToOpportunity();
        
    }
    
    public PageReference cancel(){
        return redirectToOpportunity();
    }
    
    public PageReference redirectToOpportunity(){
        return new PageReference('/' + opp.Id);
    }
}