src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Books</fullName>
                </value>
                <value>
                    <fullName>Cosmetics</fullName>
                </value>
                <value>
                    <fullName>Edibles</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Home Appliances</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Item Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_smart_pack_assembly__c</fullName>
        <label>Type of smart pack assembly</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>on roof</fullName>
                </value>
                <value>
                    <fullName>in house</fullName>
                </value>
                <value>
                    <fullName>in car</fullName>
                </value>
                <value>
                    <fullName>wall mounted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <label>Purchase Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>It_is_Smart_Pack__c</fullName>
        <defaultValue>false</defaultValue>
        <label>It is Smart Pack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Code__c</fullName>
        <formula>Item__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <formula>Item__r.Item_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <label>Purchase Order</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Quantity__c  *  Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <formula>Item__r.price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POLI-{00000}</displayFormat>
        <label>Purchase Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PurchaseOrderController.cls
public class PurchaseOrderController {
    public Purchase_Order__c purchaseOrder{get;set;}
    public Map<Id, Purchase_Order_Line_Item__c> lineItemMap{get;set;}
    private Map<Id, Purchase_Order_Line_Item__c> itemToLineItemMap;
    public List<Purchase_Order_Line_Item__c> lineItems{get;set;}
    public List<Item__c> items{get;set;}
    
    public PurchaseOrderController(){
        Id purchaseOrderId = ApexPages.currentPage().getParameters().get('id');
        purchaseOrder = [SELECT Partner_Account__r.Name, Name, Type_of_smart_pack_assembly__c FROM Purchase_Order__c WHERE Id = :purchaseOrderId];
        lineItemMap = new Map<Id, Purchase_Order_Line_Item__c>();
        itemToLineItemMap = new Map<Id, Purchase_Order_Line_Item__c>();
        String itemCategoryDefaultValue = (String)Item__c.Category__c.getDescribe().getDefaultValue();
        items = [SELECT Id, Name, Item_Name__c, Category__c, Price__c FROM Item__c ];
        for(Purchase_Order_Line_Item__c lineItem : [SELECT Id, Item__c, Item_Code__c, Item_Name__c, It_is_Smart_Pack__c, Quantity__c, Unit_Price__c, Total_Price__c FROM Purchase_Order_Line_Item__c WHERE Purchase_Order__c = :purchaseOrder.Id]){
           lineItemMap.put(lineItem.Id, lineItem);
           itemToLineItemMap.put(lineItem.Item__c, lineItem); 
        }
        lineItems  = lineItemMap.values();
    }
    
    public void saveLineItem(){
        id lineItemId = ApexPages.currentPage().getParameters().get('lId');
        Decimal quantity = lineItemMap.get(lineItemId).Quantity__c;
        handleLineItemUpdate(lineItemId, Quantity);
    }
    
    public void deleteLineItem(){
        id lineItemId = ApexPages.currentPage().getParameters().get('lId');
        handleLineItemUpdate(lineItemId, 0);
    }
    
    public void addItem(){
        Id itemId = ApexPages.currentPage().getParameters().get('itemId');
        System.debug(itemId);
        Purchase_Order_Line_Item__c lineItem = itemToLineItemMap.get(itemId);
        if(lineItem == null){
            createLineItem(1, itemId);
        }else{
            Decimal quantity = lineItem.Quantity__c + 1;
            handleLineItemUpdate(lineItem.Id, quantity);
        }
    }
    
    private void createLineItem(Decimal quantity, Id itemId){
        Purchase_Order_Line_Item__c lineItem = new Purchase_Order_Line_Item__c(Item__c = itemId, Purchase_Order__c = purchaseOrder.Id, Quantity__c = quantity);
        insert lineItem;
        reloadLineItem(lineItem.Id);
    }
    
    private void handleLineItemUpdate(Id lineItemId, Decimal quantity){
        if(quantity == 0){
            Purchase_Order_Line_Item__c lineItem = [SELECT Id, Item__c FROM Purchase_Order_Line_Item__c WHERE Id = :lineItemId];
            delete lineItem;
            lineItemMap.remove(lineItemId);
            itemToLineItemMap.remove(lineItem.Item__c);
            lineItems = lineItemMap.values();
        }else{
            Purchase_Order_Line_Item__c lineItem = new Purchase_Order_Line_Item__c(Id = lineItemId, Quantity__c = quantity);
        	update lineItem;
            reloadLineItem(lineItemId);
        }
    }
    
    private void reloadLineItem(Id lineItemId){
        Purchase_Order_Line_Item__c lineItem = [SELECT Id, Item__c, Item_Code__c, Item_Name__c, It_is_Smart_Pack__c, Quantity__c, Unit_Price__c, Total_Price__c FROM Purchase_Order_Line_Item__c WHERE Id = :lineItemId];
        lineItemMap.put(lineItemId, lineItem);
        itemToLineItemMap.put(lineItem.Item__c, lineItem);
        lineItems = lineItemMap.values();
    }
    
    
}