src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityManager.cls
public class OpportunityManager {
    public Static void updateManager(List<Opportunity> opportunities){
        //Query opportunities with the Bill_To_Contact field if not done by the caller.  
        List<Id> opportunityIds = new List<Id>();
        for(Opportunity opp : Opportunities){
            opportunityIds.add(opp.Id);
        }
        opportunities = [SELECT Id, Bill_To_Contact__c FROM Opportunity WHERE Id IN :opportunityIds];
        for(Opportunity opp : opportunities){
            if(opp.Bill_To_Contact__c != null){
                opp.Manager__c = [SELECT AccountId FROM Contact WHERE Id = :opp.Bill_To_Contact__c].AccountId;
            }
        }
        update opportunities;
    }
}