src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>Year(TODAY()) - YEAR(DOB__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Married__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Married</label>
        <type>Checkbox</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DeleteStudentsController.cls
public class DeleteStudentsController {
    public ApexPages.StandardSetController controller{get;set;}
    public List<Student__c> selectedStudents{get;private set;}
    public Boolean hasRecordsToDelete{get;set;}
    public DeleteStudentsController(ApexPages.StandardSetController con){
        this.controller = con;
        if(!Test.isRunningTest()){
     		controller.addFields(new List<String>{'FirstName__c','LastName__c','DOB__c','Age__c','Married__c'});       
        }
        selectedStudents = controller.getSelected();
        if(selectedStudents.size() == 0){
            hasRecordsToDelete = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No records selected'));
        }else{
            hasRecordsToDelete = true;
        }    
    }
    
    public PageReference deleteRecords(){
        delete selectedStudents;
        return returnToListView();
    }
	
    public pageReference cancel(){
        return returnToListView();
    }
    
    private PageReference returnToListView(){
        return controller.cancel();
    }
}