src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentJsonFormatterExtension.cls
public class StudentJsonFormatterExtension {
    public String studentAsJson{get;set;}
    public StudentJsonFormatterExtension(ApexPages.StandardController controller) {
        List<String> studentFields = new List<String>(Student__c.SObjectType.getDescribe().fields.getMap().keySet());
        controller.addFields(studentFields);
        Student__c student = (Student__c)controller.getRecord();
        System.debug(student.FirstName__c);
        studentAsJson = JSon.serializePretty(student);
    }
}